/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_litongjava_media_NativeMedia */

#ifndef _Included_com_litongjava_media_NativeMedia
#define _Included_com_litongjava_media_NativeMedia
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_litongjava_media_NativeMedia
 * Method:    splitMp3
 * Signature: (Ljava/lang/String;J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_litongjava_media_NativeMedia_splitMp3(JNIEnv *, jclass, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
